version: 2
jobs:
 build:
  docker:
   - image: registry.fedoraproject.org/fedora-minimal:31
  steps:
   - run:
      command: |
        microdnf install \
          make \
          rpmdevtools \
          gcc-gnat \
          gprbuild \
          git \
          openssh-server \
          tar \
          gzip \
          ca-certificates && \
        microdnf clean all

   - checkout:
      path: spawn
   - run: rpmdev-setuptree; cp spawn/.circleci/spawn.spec ~/rpmbuild/SPECS/
   - run: tar czf ~/rpmbuild/SOURCES/spawn.tar.gz --exclude-vcs spawn
   - run: . /etc/profile.d/gnat-project.sh; rpmbuild -ba ~/rpmbuild/SPECS/spawn.spec
   - run: |
      curl -T "$HOME/rpmbuild/RPMS/x86_64/spawn{,-devel}-0.1.0-git.fc31.x86_64.rpm" \
       -ureznikmm:$API_KEY -H "X-Bintray-Publish: 1" -H "X-Bintray-Override: 1" \
       https://api.bintray.com/content/reznikmm/matreshka/spawn/0.1.0-git/
