on: [push]
name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and deploy RPM
    steps:
      - uses: actions/checkout@v2
        with:
          path: spawn
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1.1
        with:
          args: --root spawn lint
      - name: Build RPM
        uses: reznikmm/fedora-ada-action@v2
        with:
          spec: spawn/packages/spawn.spec
      - name: Upload to bintray
        uses: reznikmm/upload-bintray-docker-action@v2
        if: ${{ github.ref == 'master' }}
        with:
          username: reznikmm
          repository: matreshka
          package: spawn
          version: head-fc32
          sourcePath: x86_64/*
          override: 1
          apiKey: ${{secrets.BINTRAY_API_KEY}}