on:
  push:
    branches:
      - master
name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and deploy RPM
    steps:
      - uses: actions/checkout@v2
        with:
          path: spawn
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1.1
        with:
          args: --root spawn lint
      - name: Build RPM
        uses: reznikmm/fedora-ada-action@v3
        with:
          spec: spawn/packages/spawn.spec
      - name: Upload tar-ball to Bintray
        uses: reznikmm/upload-bintray-action@v3
        with:
          subject: reznikmm
          repository: matreshka
          package: spawn
          version: head-fc33
          sourcePath: x86_64/*
          override: 1
          username: reznikmm
          apiKey: ${{secrets.BINTRAY_API_KEY}}
